const ONE_MINUTE_MS = 60 * 1000
const ONE_HOUR_MS = 60 * ONE_MINUTE_MS
const ONE_DAY_MS = 24 * ONE_HOUR_MS

const DEFAULT_TOKEN_LIFESPAN_MS = 14 * ONE_DAY_MS
const RESET_PASSWORD_CODE_LIFESPAN = ONE_HOUR_MS

module.exports = {
  DEFAULT_TOKEN_LIFESPAN_MS,
  RESET_PASSWORD_CODE_LIFESPAN
}